Document: nflynntest
Title: Debian nflynntest Manual
Author: <insert document author here>
Abstract: This manual describes what nflynntest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nflynntest/nflynntest.sgml.gz

Format: postscript
Files: /usr/share/doc/nflynntest/nflynntest.ps.gz

Format: text
Files: /usr/share/doc/nflynntest/nflynntest.text.gz

Format: HTML
Index: /usr/share/doc/nflynntest/html/index.html
Files: /usr/share/doc/nflynntest/html/*.html
